In [2]:
import pandas as pd

In [3]:
data = pd.read_html('https://fbref.com/es/comps/9/2022-2023/gca/Estadisticas-2022-2023-Premier-League',encoding='UTF-8',header=1)

In [12]:
data[0].sort_values(by="Dis",ascending=False)

,Equipo,PL,90 s,ACT,SCA90,PassLive,PassDead,HASTA,Dis,FR,Def,ACG,GCA90,PassLive.1,PassDead.1,HASTA.1,Dis.1,FR.1,Def.1
14,Newcastle Utd,27,38.0,1008,26.53,690,110,62,77,57,12,106,2.79,64,6,15,10,6,5
12,Manchester City,24,38.0,1099,28.92,826,81,53,76,49,14,168,4.42,130,7,8,9,12,2
11,Liverpool,28,38.0,1046,27.53,778,85,56,75,33,19,129,3.39,97,9,7,8,7,1
0,Arsenal,26,38.0,1045,27.50,776,78,57,73,43,18,150,3.95,121,6,5,13,3,2
4,Brighton,29,38.0,1075,28.29,819,73,81,63,27,12,115,3.03,83,3,13,9,6,1
13,Manchester Utd,26,38.0,1051,27.66,840,58,46,63,35,9,99,2.61,79,3,8,5,4,0
18,West Ham,25,38.0,817,21.50,586,81,40,60,35,15,67,1.76,41,6,6,8,6,0
17,Tottenham,29,38.0,910,23.95,692,60,46,55,38,19,116,3.05,84,7,7,9,7,2
7,Everton,28,38.0,735,19.34,493,84,39,54,45,20,59,1.55,41,5,5,2,4,2
8,Fulham,29,38.0,751,19.76,528,78,29,54,47,15,90,2.37,56,9,5,11,7,2
9,Leeds United,29,38.0,783,20.61,535,99,32,54,48,15,69,1.82,43,7,4,9,3,3
16,Southampton,36,38.0,718,18.89,493,77,46,51,38,13,61,1.61,35,5,7,5,6,3
10,Leicester City,28,38.0,744,19.58,540,52,50,50,38,14,87,2.29,59,2,8,8,7,3
6,Crystal Palace,26,38.0,746,19.63,497,67,56,49,59,18,67,1.76,43,6,6,6,4,2
19,Wolves,32,38.0,713,18.76,520,62,31,47,42,11,44,1.16,32,1,3,6,1,1
3,Brentford,25,38.0,702,18.47,475,99,32,45,44,7,98,2.58,65,8,4,8,11,2
2,Bournemouth,31,38.0,616,16.21,444,45,53,43,24,7,64,1.68,44,5,4,8,2,1
5,Chelsea,32,38.0,859,22.61,667,66,42,42,31,11,68,1.79,57,3,2,2,4,0
1,Aston Villa,26,38.0,751,19.76,565,50,48,38,40,10,84,2.21,55,2,6,12,6,3
15,Nott'ham Forest,33,38.0,593,15.61,416,59,31,38,36,13,54,1.42,31,5,4,11,3,0

In [12]:
data = pd.read_html('https://www.fichajes.com/inglaterra/premier-league/estadistica-jugadores/regates-completados',encoding='UTF8')

In [14]:
data[0]

     #       Jugadores  Total  por partido
0    1        M. Kudus     42          3.2
1    2         J. Doku     41          2.9
2    3       A. Fatawu     29          2.6
3    4       I. Ndiaye     40          2.4
4    5         Savinho     35          2.3
5    6      A. Semenyo     39          2.3
6    7       J. Sancho     26          2.2
7    8   Matheus Cunha     38          2.1
8    9          E. Eze     29          2.1
9   10         B. Saka     33          2.1
10  11   O. Hutchinson     34          2.0
11  12       K. Mitoma     35          1.9
12  13       M. Rogers     34          1.9
13  14        J. Bowen     33          1.8
14  15        A. Broja      5          1.7
15  16    R. Aït-Nouri     28          1.6
16  17       J. Ramsey     16          1.6
17  18  A. Wan-Bissaka     27          1.6
18  18   Mohamed Salah     27          1.6
19  20       K. Mainoo     19          1.6