In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
data = pd.read_html("https://www.espn.com.mx/futbol-americano/nfl/estadisticas/jugador", encoding='UTF-8')

In [17]:
data[0]
data[1]['Nombre']=data[0]['Nombre']

In [22]:
data[1]=data[1].drop('Nombre', axis=1)
data[1].insert(0,'Nombre',data[0]['Nombre'])

In [24]:
data[1]

,Nombre,POS,GP,CMP,ATT,CMP%,YDS,AVG,YDS/G,LNG,TD,INT,SACK,SYL,QBR,RTG
0,Joe BurrowCIN,QB,16,423,606,69.8,4641,7.7,290.1,70,42,8,44,247,76.6,109.8
1,Geno SmithSEA,QB,16,387,551,70.2,4097,7.4,256.1,71,17,15,48,325,52.9,90.5
2,Jared GoffDET,QB,15,337,472,71.4,4095,8.7,273.0,82,33,10,27,203,66.6,112.2
3,Lamar JacksonBAL,QB,16,300,442,67.9,3955,8.9,247.2,84,39,4,23,149,77.6,121.6
4,Patrick MahomesKC,QB,16,392,581,67.5,3928,6.8,245.5,54,26,11,36,239,68.4,93.5
5,Baker MayfieldTB,QB,15,359,506,70.9,3920,7.7,261.3,57,34,15,37,233,57.3,103.5
6,Sam DarnoldMIN,QB,15,310,461,67.2,3776,8.2,251.7,97,32,11,45,306,62.2,105.4
7,Matthew StaffordLAR,QB,16,340,517,65.8,3762,7.3,235.1,69,20,8,28,213,64.7,93.7
8,C.J. StroudHOU,QB,16,330,526,62.7,3677,7.0,229.8,67,19,12,52,408,49.2,86.0
9,Kyler MurrayARI,QB,16,347,506,68.6,3609,7.1,225.6,60,17,11,30,220,66.7,91.1
10,Josh AllenBUF,QB,15,291,456,63.8,3549,7.8,236.6,64,26,6,14,63,76.9,101.2
11,Justin HerbertLAC,QB,16,304,468,65.0,3524,7.5,220.3,66,21,3,40,234,61.9,99.9
12,Aaron RodgersNYJ,QB,15,333,530,62.8,3511,6.6,234.1,71,24,8,33,259,51.5,90.8
13,Kirk CousinsATL,QB,14,303,453,66.9,3508,7.7,250.6,60,18,16,28,201,51.9,88.6
14,Brock PurdySF,QB,14,273,420,65.0,3487,8.3,249.1,76,17,10,29,144,65.6,94.4
15,Bo NixDEN,QB,16,350,538,65.1,3454,6.4,215.9,93,25,12,24,198,54.3,89.2
16,Caleb WilliamsCHI,QB,16,330,533,61.9,3393,6.4,212.1,47,19,6,67,459,46.0,87.4
17,Jayden DanielsWSH,QB,15,301,432,69.7,3303,7.6,220.2,86,22,8,38,189,72.0,101.3
18,Jordan LoveGB,QB,13,242,383,63.2,3135,8.2,241.2,70,24,11,11,77,68.0,97.8
19,Jalen HurtsPHI,QB,15,248,361,68.7,2903,8.0,193.5,67,18,5,38,271,66.3,103.7
20,Tua TagovailoaMIA,QB,11,291,399,72.9,2867,7.2,260.6,80,19,7,21,154,59.7,101.4
21,Russell WilsonPIT,QB,10,197,305,64.6,2334,7.7,233.4,46,15,5,29,190,52.7,97.4
22,Drake MayeNE,QB,12,225,337,66.8,2276,6.8,189.7,40,15,10,33,220,58.6,88.3
23,Derek CarrNO,QB,10,189,279,67.7,2145,7.7,214.5,71,15,5,8,48,64.7,101.0
24,Jameis WinstonCLE,QB,12,181,296,61.1,2121,7.2,176.8,89,13,12,24,130,56.3,80.6
25,Daniel JonesNYG,QB,10,216,341,63.3,2070,6.1,207.0,43,8,7,29,172,47.6,79.4
26,Trevor LawrenceJAX,QB,10,172,284,60.6,2045,7.2,204.5,85,11,7,18,140,58.6,85.2
27,Gardner MinshewLV,QB,10,203,306,66.3,2013,6.6,201.3,57,9,10,29,164,37.5,81.0
28,Dak PrescottDAL,QB,8,185,286,64.7,1978,6.9,247.3,65,11,8,21,112,46.8,86.0
29,Bryce YoungCAR,QB,12,194,322,60.2,1949,6.1,162.4,83,10,9,24,148,47.0,76.2
30,Will LevisTEN,QB,11,181,284,63.7,1916,6.7,174.2,98,12,12,40,225,30.3,79.8
31,Anthony RichardsonIND,QB,11,126,264,47.7,1814,6.9,164.9,69,8,12,14,115,46.4,61.6
32,Cooper RushDAL,QB,11,172,280,61.4,1697,6.1,154.3,64,11,3,12,88,40.6,87.2
33,Mac JonesJAX,QB,8,136,208,65.4,1273,6.1,159.1,62,5,7,10,80,35.9,76.1
34,Mason RudolphTEN,QB,6,120,188,63.8,1267,6.7,211.2,47,8,8,7,48,54.2,79.8
35,Joe FlaccoIND,QB,6,113,170,66.5,1167,6.9,194.5,65,9,5,13,101,54.5,91.5
36,Aidan O'ConnellLV,QB,7,110,174,63.2,1156,6.6,165.1,58,4,3,9,72,39.1,82.9
37,Deshaun WatsonCLE,QB,7,137,216,63.4,1148,5.3,164.0,35,5,3,33,191,23.1,79.0
38,Justin FieldsPIT,QB,10,106,161,65.8,1106,6.9,110.6,55,5,1,16,124,52.8,93.3
39,Andy DaltonCAR,QB,6,106,160,66.3,989,6.2,164.8,39,7,6,7,37,56.5,82.0
40,Spencer RattlerNO,QB,5,84,150,56.0,859,5.7,171.8,41,2,3,17,97,36.3,68.7
41,Jacoby BrissettNE,QB,8,95,161,59.0,826,5.1,103.3,50,2,1,18,119,43.2,74.2
42,Drew LockNYG,QB,6,68,129,52.7,624,4.8,104.0,23,1,4,12,88,32.9,55.8
43,Desmond RidderLV,QB,5,51,83,61.4,447,5.4,89.4,28,2,2,10,64,30.1,73.7
44,Malik WillisGB,QB,6,30,41,73.2,414,10.1,69.0,51,3,0,5,16,88.9,129.5
45,Tyler HuntleyMIA,QB,3,39,66,59.1,377,5.7,125.7,25,1,1,7,45,23.5,73.9
46,Tim BoyleMIA/NYG,QB,3,27,50,54.0,276,5.5,92.0,30,1,1,2,11,33.4,68.4
47,Tommy DeVitoNYG,QB,3,31,44,70.5,257,5.8,85.7,23,0,0,6,31,26.9,85.1
48,Dorian Thompson-RobinsonCLE,QB,5,35,68,51.5,257,3.8,51.4,29,0,5,6,35,17.8,30.1
49,Michael Penix Jr.ATL,QB,3,21,32,65.6,240,7.5,80.0,22,0,1,1,0,50.7,75.0

In [33]:
data_defenciva = pd.read_html('https://www.espn.com.mx/futbol-americano/nfl/estadisticas/jugador/_/vista/defensiva',encoding='UTF8',header=1)

In [34]:
data_defenciva[0]
#data_defenciva[1]=data_defenciva[1].drop('Nombre', axis=1)
data_defenciva[1].insert(0,'Nombre',data_defenciva[0]['Nombre'])

In [35]:
data_defenciva[1]

,Nombre,POS,GP,SOLO,AST,TOT,SACK,YDS,TFL,PD,INT,YDS.1,LNG,TD,FF,FR,FTD
0,Budda BakerARI,S,16,91,64,155,2.0,13,9,5,0,0,0,0,0,0,0
1,Zaire FranklinIND,LB,15,83,68,151,2.5,4,6,5,2,4,4,0,3,0,0
2,Roquan SmithBAL,LB,15,78,66,144,1.5,3,4,4,1,0,0,0,1,1,0
3,Zack BaunPHI,LB,15,92,52,144,3.5,23,11,3,1,0,0,0,5,1,0
4,Daiyan HenleyLAC,LB,16,82,60,142,1.0,1,7,7,0,0,0,0,0,0,0
5,Jamien SherwoodNYJ,LB,15,90,52,142,2.0,11,9,2,0,0,0,0,0,0,0
6,Germaine PrattCIN,LB,16,78,59,137,0.0,0,4,6,2,26,24,0,2,2,0
7,Christian RozeboomLAR,LB,16,69,66,135,1.0,6,5,4,1,16,16,0,0,0,0
8,Robert SpillaneLV,LB,15,81,53,134,1.0,6,8,5,2,0,0,0,0,0,0
9,Kaden EllissATL,LB,15,75,56,131,5.0,37,8,2,0,0,0,0,1,1,0
10,Nick CrossIND,S,15,82,49,131,1.0,2,5,5,3,25,20,0,1,0,0
11,E.J. SpeedIND,LB,13,87,42,129,0.0,0,7,4,1,12,12,0,0,0,0
12,Ernest Jones IVSEA/TEN,LB,15,74,55,129,0.0,0,4,4,1,12,12,0,1,0,0
13,Jordyn BrooksMIA,LB,15,75,53,128,3.0,19,10,5,0,0,0,0,0,2,0
14,Nakobe DeanPHI,LB,15,80,48,128,3.0,26,9,4,1,0,0,0,1,2,0
15,Kyzir WhiteARI,LB,16,55,72,127,2.5,15,8,2,1,0,0,0,0,1,0
16,T.J. EdwardsCHI,LB,16,77,48,125,3.0,18,11,3,1,0,0,0,1,1,0
17,Eric KendricksDAL,LB,13,63,61,124,3.0,8,3,3,2,15,8,0,3,1,0
18,Patrick QueenPIT,LB,16,62,62,124,0.0,0,5,6,0,0,0,0,1,1,0
19,Bobby WagnerWSH,LB,15,71,47,118,2.0,13,8,2,0,0,0,0,1,2,0
20,Fred WarnerSF,LB,15,68,49,117,1.0,0,3,7,2,70,45,1,4,0,0
21,Kevin Byard IIICHI,S,16,71,45,116,1.0,3,4,7,1,0,0,0,0,2,0
22,Jack CampbellDET,LB,15,63,53,116,1.5,5,5,5,0,0,0,0,1,0,0
23,Demario DavisNO,LB,14,57,57,114,2.0,0,4,6,1,0,0,0,0,0,0
24,Brandon JonesDEN,S,15,79,35,114,0.0,0,2,10,3,74,37,0,1,1,0
25,Lavonte DavidTB,LB,15,71,41,112,5.5,44,9,5,1,7,7,0,3,1,0
26,Jahlani TavaiNE,LB,16,58,53,111,1.0,7,7,5,1,0,0,0,0,0,0
27,Quentin LakeLAR,S,16,73,38,111,2.0,7,1,5,0,0,0,0,0,0,0
28,Dorian WilliamsBUF,LB,15,65,43,108,0.0,0,5,0,0,0,0,0,1,3,0
29,Micah McFaddenNYG,LB,14,60,47,107,3.0,4,8,1,0,0,0,0,1,1,0
30,Nick BoltonKC,LB,16,73,33,106,3.0,28,11,6,1,0,0,0,1,2,0
31,Logan WilsonCIN,LB,11,55,49,104,0.0,0,2,1,0,0,0,0,2,2,0
32,Kyle HamiltonBAL,S,16,74,30,104,2.0,19,4,9,1,0,0,0,2,1,0
33,Cody BartonDEN,LB,16,52,51,103,1.5,3,2,5,2,71,56,0,1,1,1
34,Julian LoveSEA,S,16,75,28,103,0.0,0,3,9,2,26,26,0,2,1,0
35,Xavier WoodsCAR,S,15,64,38,102,0.0,0,2,5,3,70,33,0,0,0,0
36,Quay WalkerGB,LB,13,72,30,102,2.5,19,9,2,0,0,0,0,0,0,0
37,Henry To'oTo'oHOU,LB,14,52,50,102,1.5,1,7,3,1,0,0,0,1,0,0
38,Tremaine EdmundsCHI,LB,16,56,45,101,1.0,7,3,7,1,0,0,0,1,0,0
39,Devin LloydJAX,LB,14,53,48,101,1.0,5,5,3,0,0,0,0,1,0,0
40,DeShon ElliottPIT,S,14,66,34,100,0.0,0,4,6,1,0,0,0,2,3,0
41,Jeremy ChinnWSH,S,15,63,36,99,1.0,9,5,3,1,0,0,0,1,2,0
42,Grant DelpitCLE,S,14,57,41,98,1.0,9,6,1,0,0,0,0,0,1,0
43,Terrel BernardBUF,LB,12,55,43,98,1.0,6,5,3,2,1,1,0,0,1,0
44,Tyler NubinNYG,S,13,57,41,98,0.0,0,4,1,0,0,0,0,1,1,0
45,Josey JewellCAR,LB,12,51,46,97,3.5,26,7,7,1,0,0,0,0,2,0
46,Quincy WilliamsNYJ,LB,15,62,35,97,2.0,22,8,2,0,0,0,0,3,2,0
47,Brian BranchDET,S,14,72,24,96,0.0,0,7,15,4,48,47,0,1,0,0
48,Josh MetellusMIN,S,15,57,38,95,0.0,0,2,4,2,16,12,0,1,0,0
49,Kenneth Murray Jr.TEN,LB,14,57,38,95,3.5,13,8,2,1,6,6,0,1,0,0

In [38]:
data[1][data[1]['Nombre'].str.contains('Allen', case=False, na=False)]

,Nombre,POS,GP,CMP,ATT,CMP%,YDS,AVG,YDS/G,LNG,TD,INT,SACK,SYL,QBR,RTG
10,Josh AllenBUF,QB,15,291,456,63.8,3549,7.8,236.6,64,26,6,14,63,76.9,101.2