In [22]:
import pandas as pd
import numpy as np

def extr_url_seriea(urlpath):

    data = pd.read_html('https://fbref.com/es/comps/11/2019-2020/horario/Marcadores-y-partidos-de-2019-2020-Serie-A')
    data = data[0]
    for i in range(0,5):
        urlname = '202'+str(i)+'-'+'202'+str(i+1)+'/horario/Marcadores-y-partidos-de-202'+str(i)+'-202'+str(i+1)+'-Serie-A'
        url = urlpath + urlname 

        sesons_data = pd.read_html(url)
        sesons_data = sesons_data[0]
        data = pd.concat([data, sesons_data],axis=0)
    return data

In [23]:
import re
def extraer_numero(cadena):
    numeros = re.findall(r'\b\d+\b', str(cadena))
    if numeros:
        return int(numeros[0])
    else:
        return None

In [24]:
urlpath = 'https://fbref.com/es/comps/11/'
data = extr_url_seriea(urlpath)

In [25]:
data = data.drop('Notas',axis=1)

In [18]:
data = data.drop('Ronda',axis=1)
data

,Sem.,Día,Fecha,Hora,Local,xG,Marcador,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido
0,1.0,Sáb,2019-08-24,18:00,Parma,0.3,0–1,1.4,Juventus,20073.0,Stadio Ennio Tardini,Fabio Maresca,Informe del partido
1,1.0,Sáb,2019-08-24,20:45,Fiorentina,1.7,3–4,2.0,Napoli,33614.0,Stadio Artemio Franchi,Davide Massa,Informe del partido
2,1.0,Dom,2019-08-25,18:00,Udinese,0.8,1–0,0.7,Milan,24584.0,Dacia Arena,Fabrizio Pasqua,Informe del partido
3,1.0,Dom,2019-08-25,20:45,SPAL,1.6,2–3,1.8,Atalanta,11706.0,Stadio Paolo Mazza,Gianluca Manganiello,Informe del partido
4,1.0,Dom,2019-08-25,20:45,Roma,2.5,3–3,1.3,Genoa,38779.0,Stadio Olimpico,Giampaolo Calvarese,Informe del partido
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,38.0,Dom,2025-05-25,NaN,Udinese,NaN,NaN,NaN,Fiorentina,NaN,Bluenergy Stadium,NaN,Cara a cara
414,38.0,Dom,2025-05-25,NaN,Atalanta,NaN,NaN,NaN,Parma,NaN,Gewiss Stadium,NaN,Cara a cara
415,38.0,Dom,2025-05-25,NaN,Bologna,NaN,NaN,NaN,Genoa,NaN,Stadio Renato Dall'Ara,NaN,Cara a cara
416,38.0,Dom,2025-05-25,NaN,Empoli,NaN,NaN,NaN,Hellas Verona,NaN,Stadio Carlo Castellani - Computer Gross...,NaN,Cara a cara
417,38.0,Dom,2025-05-25,NaN,Torino,NaN,NaN,NaN,Roma,NaN,Stadio Olimpico Grande Torino,NaN,Cara a cara

In [19]:
data[['Goles Local', 'Goles Visitante']] = data['Marcador'].str.split('–', expand=True)
data = data.drop('Marcador', axis=1)
data['Goles Local'] = data['Goles Local'].apply(extraer_numero).fillna(0).astype(int)
data['Goles Visitante'] = data['Goles Visitante'].apply(extraer_numero).fillna(0).astype(int)
data = data.reset_index(drop=True)

In [20]:
data = data.dropna(subset=['Árbitro'])

In [21]:
data

,Sem.,Día,Fecha,Hora,Local,xG,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido,Goles Local,Goles Visitante
0,1.0,Sáb,2019-08-24,18:00,Parma,0.3,1.4,Juventus,20073.0,Stadio Ennio Tardini,Fabio Maresca,Informe del partido,0,1
1,1.0,Sáb,2019-08-24,20:45,Fiorentina,1.7,2.0,Napoli,33614.0,Stadio Artemio Franchi,Davide Massa,Informe del partido,3,4
2,1.0,Dom,2019-08-25,18:00,Udinese,0.8,0.7,Milan,24584.0,Dacia Arena,Fabrizio Pasqua,Informe del partido,1,0
3,1.0,Dom,2019-08-25,20:45,SPAL,1.6,1.8,Atalanta,11706.0,Stadio Paolo Mazza,Gianluca Manganiello,Informe del partido,2,3
4,1.0,Dom,2019-08-25,20:45,Roma,2.5,1.3,Genoa,38779.0,Stadio Olimpico,Giampaolo Calvarese,Informe del partido,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2316,20.0,Sáb,2025-01-11,20:45,Milan,2.7,0.4,Cagliari,NaN,Stadio Giuseppe Meazza,Francesco Fourneau,Informe del partido,1,1
2317,20.0,Dom,2025-01-12,12:30,Genoa,1.2,0.4,Parma,NaN,Stadio Comunale Luigi Ferraris,Andrea Colombo,Informe del partido,1,0
2318,20.0,Dom,2025-01-12,15:00,Venezia,0.4,1.9,Inter,NaN,Stadio Pier Luigi Penzo,Marco Piccinini,Informe del partido,0,1
2319,20.0,Dom,2025-01-12,18:00,Bologna,2.0,1.4,Roma,NaN,Stadio Renato Dall'Ara,Rosario Abisso,Informe del partido,2,2
2320,20.0,Dom,2025-01-12,20:45,Napoli,1.1,0.3,Hellas Verona,NaN,Stadio Diego Armando Maradona,Luca Zufferli,Informe del partido,2,0