In [1]:
!pip install statsbombpy

Collecting statsbombpy
  Downloading statsbombpy-1.14.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 916.5 kB/s eta 0:00:0031m2.7 MB/s eta 0:00:01
Requirement already satisfied: pandas in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from statsbombpy) (2.2.3)
Requirement already satisfied: requests in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from statsbombpy) (2.32.3)
Collecting requests-cache (from statsbombpy)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Collecting inflect (from statsbombpy)
  Downloading inflect-7.5.0-py3-none-any.whl.metadata (24 kB)
Collecting joblib (from statsbombpy)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting more_itertools>=8.5.0 (from inflect->statsbombpy)
  Downloading more_itertools-10.5.0-py3-none-any.whl.metadata (36 kB)
Collecting typeguard>=4.0.1 (from inflect->statsbombpy)
  Downloading typeguard-4.4.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: numpy>=1.26.0 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from pandas->statsbombpy) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from pandas->statsbombpy) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from pandas->statsbombpy) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from requests->statsbombpy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from requests->statsbombpy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from requests->statsbombpy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from requests->statsbombpy) (2024.12.14)
Requirement already satisfied: attrs>=21.2 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from requests-cache->statsbombpy) (24.3.0)
Collecting cattrs>=22.2 (from requests-cache->statsbombpy)
  Downloading cattrs-24.1.2-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from requests-cache->statsbombpy) (4.3.6)
Collecting url-normalize>=1.4 (from requests-cache->statsbombpy)
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: six>=1.5 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/emmanuel/ML_begin/ml/lib/python3.12/site-packages (from typeguard>=4.0.1->inflect->statsbombpy) (4.12.2)
Downloading statsbombpy-1.14.0-py3-none-any.whl (16 kB)
Downloading inflect-7.5.0-py3-none-any.whl (35 kB)
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 kB 1.1 MB/s eta 0:00:00[36m0:00:01m eta 0:00:01
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 1.2 MB/s eta 0:00:00
Downloading cattrs-24.1.2-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 796.7 kB/s eta 0:00:001m1.9 MB/s eta 0:00:01
Downloading more_itertools-10.5.0-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.0 MB/s eta 0:00:00
Downloading typeguard-4.4.1-py3-none-any.whl (35 kB)
Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Installing collected packages: url-normalize, typeguard, more_itertools, joblib, cattrs, requests-cache, inflect, statsbombpy
Successfully installed cattrs-24.1.2 inflect-7.5.0 joblib-1.4.2 more_itertools-10.5.0 requests-cache-1.2.1 statsbombpy-1.14.0 typeguard-4.4.1 url-normalize-1.4.3

In [2]:
from statsbombpy import sb

In [27]:
competencia=sb.competitions()

/home/emmanuel/ML_begin/ml/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [40]:
competencia[competencia['competition_name']=='Premier League']

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
64,2,27,England,Premier League,male,False,False,2015/2016,2024-06-12T07:43:56.243851,2021-06-13T16:17:31.694,None,2024-06-12T07:43:56.243851
65,2,44,England,Premier League,male,False,False,2003/2004,2024-03-08T14:49:13.195793,2021-06-13T16:17:31.694,None,2024-03-08T14:49:13.195793

In [41]:
sb.matches(competition_id=2, season_id=27)

/home/emmanuel/ML_begin/ml/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3754058,2016-01-02,16:00:00.000,England - Premier League,2015/2016,Leicester City,AFC Bournemouth,0,0,available,...,2021-06-12T16:17:31.694,20,Regular Season,King Power Stadium,Andre Marriner,Claudio Ranieri,Eddie Howe,1.1.0,2,2
1,3754245,2015-10-17,16:00:00.000,England - Premier League,2015/2016,West Bromwich Albion,Sunderland,1,0,available,...,2021-06-13T16:17:31.694,9,Regular Season,The Hawthorns,Martin Atkinson,Tony Pulis,Sam Allardyce,1.1.0,2,2
2,3754136,2015-12-19,18:30:00.000,England - Premier League,2015/2016,Newcastle United,Aston Villa,1,1,available,...,2021-06-13T16:17:31.694,17,Regular Season,St. James'' Park,Martin Atkinson,Steve McClaren,Rémi Garde,1.1.0,2,2
3,3754037,2016-04-30,16:00:00.000,England - Premier League,2015/2016,Everton,AFC Bournemouth,2,1,available,...,2021-06-12T16:17:31.694,36,Regular Season,Goodison Park,Neil Swarbrick,Roberto Martínez Montoliú,Eddie Howe,1.1.0,2,2
4,3754039,2016-02-13,16:00:00.000,England - Premier League,2015/2016,Crystal Palace,Watford,1,2,available,...,2021-06-12T16:17:31.694,26,Regular Season,Selhurst Park,Robert Madley,Alan Pardew,Enrique Sánchez Flores,1.1.0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,3754020,2015-08-17,21:00:00.000,England - Premier League,2015/2016,Liverpool,AFC Bournemouth,1,0,available,...,2021-06-13T16:17:31.694,2,Regular Season,Anfield,Craig Pawson,Brendan Rodgers,Eddie Howe,1.1.0,2,2
376,3754267,2015-08-15,16:00:00.000,England - Premier League,2015/2016,Watford,West Bromwich Albion,0,0,available,...,2021-06-13T16:17:31.694,2,Regular Season,Vicarage Road,Paul Tierney,Enrique Sánchez Flores,Tony Pulis,1.1.0,2,2
377,3754141,2015-08-09,14:30:00.000,England - Premier League,2015/2016,Arsenal,West Ham United,0,2,available,...,2021-06-13T16:17:31.694,1,Regular Season,Emirates Stadium,Martin Atkinson,Arsène Wenger,Slaven Bilić,1.1.0,2,2
378,3754128,2015-08-08,16:00:00.000,England - Premier League,2015/2016,AFC Bournemouth,Aston Villa,0,1,available,...,2021-06-13T16:17:31.694,1,Regular Season,Vitality Stadium,Mark Clattenburg,Eddie Howe,Tim Sherwood,1.1.0,2,2
379,3754078,2015-08-08,18:30:00.000,England - Premier League,2015/2016,Chelsea,Swansea City,2,2,available,...,2021-06-13T16:17:31.694,1,Regular Season,Stamford Bridge,Michael Oliver,José Mario Felix dos Santos Mourinho,Garry Monk,1.1.0,2,2

In [9]:
sb.matches(competition_id=9, season_id=281).columns

/home/emmanuel/ML_begin/ml/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_team', 'away_team', 'home_score', 'away_score', 'match_status',
       'match_status_360', 'last_updated', 'last_updated_360', 'match_week',
       'competition_stage', 'stadium', 'referee', 'home_managers',
       'away_managers', 'data_version', 'shot_fidelity_version',
       'xy_fidelity_version'],
      dtype='object')

In [13]:
sb.matches(competition_id=9, season_id=281)

/home/emmanuel/ML_begin/ml/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3895302,2024-04-14,17:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Werder Bremen,5,0,available,...,2024-05-10T17:03:59.613154,29,Regular Season,BayArena,Harm Osmers,Xabier Alonso Olano,Ole Werner,1.1.0,2,2
1,3895292,2024-04-06,15:30:00.000,Germany - 1. Bundesliga,2023/2024,Union Berlin,Bayer Leverkusen,0,1,available,...,2024-05-12T21:08:37.897296,28,Regular Season,Stadion An der Alten Försterei,Benjamin Brand,Nenad Bjelica,Xabier Alonso Olano,1.1.0,2,2
2,3895333,2024-05-05,18:30:00.000,Germany - 1. Bundesliga,2023/2024,Eintracht Frankfurt,Bayer Leverkusen,1,5,available,...,2024-05-14T16:32:13.483516,32,Regular Season,Deutsche Bank Park,Christian Dingert,Dino Toppmöller,Xabier Alonso Olano,1.1.0,2,2
3,3895340,2024-05-12,20:30:00.000,Germany - 1. Bundesliga,2023/2024,Bochum,Bayer Leverkusen,0,5,available,...,2024-05-14T16:46:08.459843,33,Regular Season,Vonovia Ruhrstadion,Benjamin Brand,Heiko Butscher,Xabier Alonso Olano,1.1.0,2,2
4,3895348,2024-05-18,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Augsburg,2,1,available,...,2024-05-20T10:33:09.140760,34,Regular Season,BayArena,Matthias Jöllenbeck,Xabier Alonso Olano,Jess Christian Thorup,1.1.0,2,2
5,3895286,2024-03-30,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Hoffenheim,2,1,available,...,2024-05-08T03:36:21.320065,27,Regular Season,BayArena,Deniz Aytekin,Xabier Alonso Olano,Pellegrino Matarazzo,1.1.0,2,2
6,3895220,2024-02-03,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Darmstadt 98,Bayer Leverkusen,0,2,available,...,2024-05-08T01:01:15.978489,20,Regular Season,Merck-Stadion am Böllenfalltor,Tobias Reichel,Torsten Lieberknecht,Xabier Alonso Olano,1.1.0,2,2
7,3895250,2024-02-23,21:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,FSV Mainz 05,2,1,available,...,2024-05-08T00:38:33.864825,23,Regular Season,BayArena,Timo Gerach,Xabier Alonso Olano,Bo Henriksen,1.1.0,2,2
8,3895266,2024-03-10,20:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Wolfsburg,2,0,available,...,2024-04-28T10:29:53.455142,25,Regular Season,BayArena,Daniel Siebert,Xabier Alonso Olano,Niko Kovač,1.1.0,2,2
9,3895275,2024-03-17,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Freiburg,Bayer Leverkusen,2,3,available,...,2024-04-19T22:39:18.935666,26,Regular Season,Europa-Park Stadion,Harm Osmers,Christian Streich,Xabier Alonso Olano,1.1.0,2,2
10,3895180,2023-12-17,18:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Eintracht Frankfurt,3,0,available,...,2024-03-31T21:08:00.046656,15,Regular Season,BayArena,Christian Dingert,Xabier Alonso Olano,Dino Toppmöller,1.1.0,2,2
11,3895134,2023-11-04,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Hoffenheim,Bayer Leverkusen,2,3,available,...,2024-02-07T13:51:13.679007,10,Regular Season,PreZero Arena,Frank Willenborg,Pellegrino Matarazzo,Xabier Alonso Olano,1.1.0,2,2
12,3895121,2023-10-29,18:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Freiburg,2,1,available,...,2023-11-22T05:11:07.603363,9,Regular Season,BayArena,Daniel Siebert,Xabier Alonso Olano,Christian Streich,1.1.0,2,2
13,3895107,2023-10-08,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,FC Köln,3,0,available,...,2024-01-06T10:35:32.456060,7,Regular Season,BayArena,Felix Zwayer,Xabier Alonso Olano,Steffen Baumgart,1.1.0,2,2
14,3895074,2023-09-15,21:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayern Munich,Bayer Leverkusen,2,2,available,...,2024-01-26T03:49:07.013902,4,Regular Season,Allianz Arena,Daniel Schlager,Thomas Tuchel,Xabier Alonso Olano,1.1.0,2,2
15,3895139,2023-11-12,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Union Berlin,4,0,available,...,2024-01-30T20:45:30.579373,11,Regular Season,BayArena,Timo Gerach,Xabier Alonso Olano,Urs Fischer,1.1.0,2,2
16,3895086,2023-09-24,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,FC Heidenheim,4,1,available,...,2024-01-01T09:52:59.525330,5,Regular Season,BayArena,Christian Dingert,Xabier Alonso Olano,Frank Schmidt,1.1.0,2,2
17,3895320,2024-04-27,19:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,VfB Stuttgart,2,2,available,...,2024-05-13T17:38:39.789677,31,Regular Season,BayArena,Felix Zwayer,Xabier Alonso Olano,Sebastian Hoeneß,1.1.0,2,2
18,3895309,2024-04-21,17:30:00.000,Germany - 1. Bundesliga,2023/2024,Borussia Dortmund,Bayer Leverkusen,1,1,available,...,2024-05-10T14:39:35.216574,30,Regular Season,Signal-Iduna-Park,Daniel Siebert,Edin Terzić,Xabier Alonso Olano,1.1.0,2,2
19,3895258,2024-03-03,16:30:00.000,Germany - 1. Bundesliga,2023/2024,FC Köln,Bayer Leverkusen,0,2,available,...,2024-05-08T03:35:25.921876,24,Regular Season,RheinEnergieStadion,Tobias Stieler,Timo Schultz,Xabier Alonso Olano,1.1.0,2,2
20,3895244,2024-02-17,16:30:00.000,Germany - 1. Bundesliga,2023/2024,FC Heidenheim,Bayer Leverkusen,1,2,available,...,2024-04-23T00:19:29.644221,22,Regular Season,Voith-Arena,Harm Osmers,Frank Schmidt,Xabier Alonso Olano,1.1.0,2,2
21,3895232,2024-02-10,19:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Bayern Munich,3,0,available,...,2024-05-07T19:36:17.578845,21,Regular Season,BayArena,Felix Zwayer,Xabier Alonso Olano,Thomas Tuchel,1.1.0,2,2
22,3895210,2024-01-27,19:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Borussia Mönchengladbach,0,0,available,...,2024-04-28T11:15:03.792111,19,Regular Season,BayArena,Deniz Aytekin,Xabier Alonso Olano,Gerardo Seoane Castro,1.1.0,2,2
23,3895202,2024-01-20,19:30:00.000,Germany - 1. Bundesliga,2023/2024,RB Leipzig,Bayer Leverkusen,2,3,available,...,2024-03-24T11:04:42.281656,18,Regular Season,Red Bull Arena,Matthias Jöllenbeck,Marco Rose,Xabier Alonso Olano,1.1.0,2,2
24,3895194,2024-01-13,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Augsburg,Bayer Leverkusen,0,1,available,...,2024-02-28T13:48:13.756779,17,Regular Season,WWK Arena,Sven Jablonski,Jess Christian Thorup,Xabier Alonso Olano,1.1.0,2,2
25,3895182,2023-12-20,21:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Bochum,4,0,available,...,2024-03-27T11:25:34.494440,16,Regular Season,BayArena,Daniel Schlager,Xabier Alonso Olano,Thomas Letsch,1.1.0,2,2
26,3895167,2023-12-10,16:30:00.000,Germany - 1. Bundesliga,2023/2024,VfB Stuttgart,Bayer Leverkusen,1,1,available,...,2024-03-26T08:09:25.818281,14,Regular Season,MHPArena,Deniz Aytekin,Sebastian Hoeneß,Xabier Alonso Olano,1.1.0,2,2
27,3895158,2023-12-03,18:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Borussia Dortmund,1,1,available,...,2024-05-07T20:02:31.877343,13,Regular Season,BayArena,Daniel Siebert,Xabier Alonso Olano,Edin Terzić,1.1.0,2,2
28,3895153,2023-11-25,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Werder Bremen,Bayer Leverkusen,0,3,available,...,2024-03-26T09:18:16.484394,12,Regular Season,Wohninvest Weserstadion,Martin Petersen,Ole Werner,Xabier Alonso Olano,1.1.0,2,2
29,3895113,2023-10-21,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Wolfsburg,Bayer Leverkusen,1,2,available,...,2024-03-27T09:17:41.033608,8,Regular Season,Volkswagen Arena,Marco Fritz,Niko Kovač,Xabier Alonso Olano,1.1.0,2,2
30,3895095,2023-09-30,16:30:00.000,Germany - 1. Bundesliga,2023/2024,FSV Mainz 05,Bayer Leverkusen,0,3,available,...,2024-02-09T11:51:33.890250,6,Regular Season,Mewa Arena,Benjamin Brand,Bo Svensson,Xabier Alonso Olano,1.1.0,2,2
31,3895067,2023-09-02,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Darmstadt 98,5,1,available,...,2023-10-29T03:14:50.549747,3,Regular Season,BayArena,Sven Jablonski,Xabier Alonso Olano,Torsten Lieberknecht,1.1.0,2,2
32,3895060,2023-08-26,19:30:00.000,Germany - 1. Bundesliga,2023/2024,Borussia Mönchengladbach,Bayer Leverkusen,0,3,available,...,2023-12-06T10:47:16.970767,2,Regular Season,Stadion im BORUSSIA-PARK,Christian Dingert,Gerardo Seoane Castro,Xabier Alonso Olano,1.1.0,2,2
33,3895052,2023-08-19,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,RB Leipzig,3,2,available,...,2023-11-21T13:34:09.912520,1,Regular Season,BayArena,Felix Brych,Xabier Alonso Olano,Marco Rose,1.1.0,2,2

In [16]:
sorted(sb.events(match_id=3895302).columns)

/home/emmanuel/ML_begin/ml/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

['50_50',
 'bad_behaviour_card',
 'ball_receipt_outcome',
 'ball_recovery_recovery_failure',
 'block_deflection',
 'block_save_block',
 'carry_end_location',
 'clearance_aerial_won',
 'clearance_body_part',
 'clearance_head',
 'clearance_left_foot',
 'clearance_right_foot',
 'counterpress',
 'dribble_nutmeg',
 'dribble_outcome',
 'duel_outcome',
 'duel_type',
 'duration',
 'foul_committed_advantage',
 'foul_committed_card',
 'foul_committed_penalty',
 'foul_won_advantage',
 'foul_won_defensive',
 'foul_won_penalty',
 'goalkeeper_body_part',
 'goalkeeper_end_location',
 'goalkeeper_outcome',
 'goalkeeper_position',
 'goalkeeper_technique',
 'goalkeeper_type',
 'id',
 'index',
 'injury_stoppage_in_chain',
 'interception_outcome',
 'location',
 'match_id',
 'minute',
 'off_camera',
 'out',
 'pass_aerial_won',
 'pass_angle',
 'pass_assisted_shot_id',
 'pass_body_part',
 'pass_cross',
 'pass_cut_back',
 'pass_deflected',
 'pass_end_location',
 'pass_goal_assist',
 'pass_height',
 'pass_inswinging',
 'pass_length',
 'pass_outcome',
 'pass_outswinging',
 'pass_recipient',
 'pass_recipient_id',
 'pass_shot_assist',
 'pass_switch',
 'pass_technique',
 'pass_through_ball',
 'pass_type',
 'period',
 'play_pattern',
 'player',
 'player_id',
 'position',
 'possession',
 'possession_team',
 'possession_team_id',
 'related_events',
 'second',
 'shot_aerial_won',
 'shot_body_part',
 'shot_end_location',
 'shot_first_time',
 'shot_freeze_frame',
 'shot_key_pass_id',
 'shot_one_on_one',
 'shot_outcome',
 'shot_statsbomb_xg',
 'shot_technique',
 'shot_type',
 'substitution_outcome',
 'substitution_outcome_id',
 'substitution_replacement',
 'substitution_replacement_id',
 'tactics',
 'team',
 'team_id',
 'timestamp',
 'type',
 'under_pressure']

In [20]:
df_match = sb.events(match_id=3895302)
df_match = df_match[['timestamp','team','type','minute','location','pass_end_location','player']]
df_match = df_match.sort_values(['minute','timestamp'])
df_match

/home/emmanuel/ML_begin/ml/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,timestamp,team,type,minute,location,pass_end_location,player
0,00:00:00.000,Bayer Leverkusen,Starting XI,0,NaN,NaN,NaN
1,00:00:00.000,Werder Bremen,Starting XI,0,NaN,NaN,NaN
2,00:00:00.000,Bayer Leverkusen,Half Start,0,NaN,NaN,NaN
3,00:00:00.000,Werder Bremen,Half Start,0,NaN,NaN,NaN
6,00:00:03.417,Werder Bremen,Pass,0,"[61.0, 40.1]","[59.0, 40.9]",Nick Woltemade
...,...,...,...,...,...,...,...
3786,00:44:22.844,Werder Bremen,Pressure,89,"[24.4, 23.9]",NaN,Olivier Deman
4119,00:44:25.079,Bayer Leverkusen,Shot,89,"[106.4, 48.8]",NaN,Florian Wirtz
4153,00:44:25.897,Werder Bremen,Goal Keeper,89,"[5.4, 36.1]",NaN,Michael Zetterer
4208,00:44:52.108,Werder Bremen,Half End,89,NaN,NaN,NaN
4209,00:44:52.108,Bayer Leverkusen,Half End,89,NaN,NaN,NaN

In [25]:
df_match['type'].unique()

array(['Starting XI', 'Half Start', 'Pass', 'Ball Receipt*', 'Carry',
       'Pressure', 'Miscontrol', 'Dribble', 'Duel', 'Interception',
       'Ball Recovery', 'Dispossessed', 'Block', 'Foul Committed',
       'Foul Won', 'Error', 'Shot', 'Goal Keeper', 'Injury Stoppage',
       'Referee Ball-Drop', '50/50', 'Clearance', 'Offside',
       'Dribbled Past', 'Player Off', 'Player On', 'Substitution',
       'Bad Behaviour', 'Half End', 'Tactical Shift', 'Shield'],
      dtype=object)

In [26]:
df_match[df_match['type']=='Shot']

,timestamp,team,type,minute,location,pass_end_location,player
4093,00:06:48.773,Werder Bremen,Shot,6,"[100.4, 35.1]",NaN,Leonardo Bittencourt
4094,00:07:40.953,Bayer Leverkusen,Shot,7,"[114.6, 33.5]",NaN,Piero Martín Hincapié Reyna
4095,00:11:08.471,Werder Bremen,Shot,11,"[106.2, 55.8]",NaN,Julián Malatini
4096,00:13:16.073,Bayer Leverkusen,Shot,13,"[113.9, 47.4]",NaN,Jonathan Tah
4097,00:16:00.956,Bayer Leverkusen,Shot,16,"[89.2, 42.5]",NaN,Granit Xhaka
4098,00:16:31.596,Bayer Leverkusen,Shot,16,"[110.2, 32.6]",NaN,Jonathan Tah
4099,00:18:28.225,Werder Bremen,Shot,18,"[105.4, 45.1]",NaN,Nick Woltemade
4100,00:24:27.217,Bayer Leverkusen,Shot,24,"[108.0, 40.0]",NaN,Victor Okoh Boniface
4101,00:27:46.504,Bayer Leverkusen,Shot,27,"[101.5, 47.5]",NaN,Granit Xhaka
4102,00:28:21.806,Bayer Leverkusen,Shot,28,"[116.3, 46.0]",NaN,Jonathan Tah
4103,00:28:23.060,Bayer Leverkusen,Shot,28,"[116.3, 43.3]",NaN,Victor Okoh Boniface
4104,00:34:51.122,Bayer Leverkusen,Shot,34,"[109.4, 44.9]",NaN,Jonas Hofmann
4105,00:37:40.441,Bayer Leverkusen,Shot,37,"[113.1, 27.5]",NaN,Amine Adli
4106,00:43:36.743,Bayer Leverkusen,Shot,43,"[110.1, 41.6]",NaN,Edmond Fayçal Tapsoba
4107,00:45:26.691,Werder Bremen,Shot,45,"[115.9, 40.1]",NaN,Mitchell Weiser
4108,00:05:35.695,Werder Bremen,Shot,50,"[97.5, 40.8]",NaN,Leonardo Bittencourt
4109,00:13:10.827,Bayer Leverkusen,Shot,58,"[93.8, 34.8]",NaN,Florian Wirtz
4110,00:14:18.478,Bayer Leverkusen,Shot,59,"[93.0, 39.1]",NaN,Granit Xhaka
4111,00:19:10.632,Bayer Leverkusen,Shot,64,"[106.3, 29.6]",NaN,Florian Wirtz
4112,00:22:25.400,Bayer Leverkusen,Shot,67,"[93.5, 40.1]",NaN,Florian Wirtz
4113,00:25:17.218,Bayer Leverkusen,Shot,70,"[112.5, 29.6]",NaN,Patrik Schick
4114,00:26:31.458,Bayer Leverkusen,Shot,71,"[108.0, 51.1]",NaN,Jeremie Frimpong
4115,00:29:42.717,Werder Bremen,Shot,74,"[108.1, 27.2]",NaN,Olivier Deman
4116,00:29:45.835,Werder Bremen,Shot,74,"[98.2, 42.1]",NaN,Romano Schmid
4117,00:35:22.811,Bayer Leverkusen,Shot,80,"[101.6, 43.3]",NaN,Exequiel Alejandro Palacios
4118,00:37:29.786,Bayer Leverkusen,Shot,82,"[103.6, 35.0]",NaN,Florian Wirtz
4119,00:44:25.079,Bayer Leverkusen,Shot,89,"[106.4, 48.8]",NaN,Florian Wirtz